export const SITE = {
  name: 'Charter Flight Network',
  url: 'https://charterflightnetwork.com',
  tagline:
    'Private jet, turboprop, float-plane and helicopter charter flights across Canada',
  phone: '(807) 472-1955',
  phoneHref: 'tel:+18074721955',
  // TODO(owner): confirm address — legacy pages show BOTH
  // "401 A Donald St West, P7E 5Y1" and an older "1100 Memorial Avenue,
  // Suite 424, P7B 4A3". Using 401 A Donald St W per migration direction.
  // Note: a Donald St W address with a P7E postal code looks internally
  // inconsistent — verify street + postal code together.
  address: {
    street: '401 A Donald St West',
    city: 'Thunder Bay',
    region: 'ON',
    regionLong: 'Ontario',
    postalCode: 'P7E 5Y1',
    country: 'CA',
  },
  founded: 2008,
  networkSize: 'over 400 charter airlines across Canada',
  // Same claim without the region suffix, for copy that already said "Canada"
  // in the preceding sentence. Keeps the number itself in one place.
  networkSizeShort: 'over 400 charter airlines',
  disclaimer:
    'Charter Flight Network is not a charter service provider. We do not own nor operate any aircraft. All charter quotes are generated by our charter network partners.',
  facebook: 'https://www.facebook.com/charterflightnetwork',
  directoryUrl: 'https://www.canadianaircharterdirectory.com/',
  /**
   * Single source of truth for every form's submit endpoint.
   * Default: the legacy PHP FormMail script on the existing Apache host —
   * keeps the proven funnel working when dist/ is uploaded there.
   * TODO(owner): if hosting anywhere without formmailer.php (Netlify,
   * Cloudflare Pages, GitHub Pages), replace with a static form backend,
   * e.g. Web3Forms: 'https://api.web3forms.com/submit' plus an access_key
   * hidden field (free tier ~250 submissions/month; Formspree free is
   * ~50/month; Netlify Forms only on Netlify hosting).
   */
  formEndpoint: '/formmailer.php',
} as const;
