export const SITE = {
  name: 'Charter Flight Network',
  url: 'https://charterflightnetwork.com',
  tagline:
    'Private jet, turboprop, float-plane and helicopter charter flights across Canada',
  phone: '(807) 472-1955',
  phoneHref: 'tel:+18074721955',
  // TODO: confirm address — legacy pages show both "401 A Donald St W" and
  // "1100 Memorial Ave"; using 401 A Donald St W per migration direction.
  address: {
    street: '401 A Donald St West',
    city: 'Thunder Bay',
    region: 'ON',
    regionLong: 'Ontario',
    postalCode: 'P7E 5Y1',
    country: 'CA',
  },
  founded: 2008,
  networkSize: 'over 400 charter airlines across Canada',
  disclaimer:
    'Charter Flight Network is not a charter service provider. We do not own nor operate any aircraft. All charter quotes are generated by our charter network partners.',
  facebook: 'https://www.facebook.com/charterflightnetwork',
  directoryUrl: 'https://www.canadianaircharterdirectory.com/',
} as const;
