/**
 * The full pre-ship verification gate, one command:  npm run verify
 *
 * Requires a build in dist/. Starts its own preview server on :4321 (unless
 * one is already answering), runs every suite, and exits non-zero if any
 * fails — the single gate the weekly loop, the Actions workflow, and humans
 * all share, so nobody's checklist can drift from anybody else's.
 */
import { spawn, execSync } from 'node:child_process';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const results = [];
const run = (name, fn) => {
  try {
    const detail = fn();
    results.push(true);
    console.log(`PASS  ${name}${detail ? ` — ${detail}` : ''}`);
  } catch (e) {
    results.push(false);
    console.log(`FAIL  ${name} — ${String(e.message ?? e).slice(0, 300)}`);
  }
};

// ---- static checks (no server needed) --------------------------------------
run('redirects + dead links (crawl/verify.py)', () => {
  const out = execSync('python3 crawl/verify.py', { cwd: ROOT, encoding: 'utf8' });
  if (!/(\d+)\/\1 redirect targets resolve/.test(out)) throw new Error(out.trim());
  if (!/internal dead links in built site: 0/.test(out)) throw new Error(out.trim());
  return out.trim().replace(/\n/g, ' · ');
});

run('disclaimer verbatim on every page', () => {
  const needle =
    'Charter Flight Network is not a charter service provider. We do not own nor operate any aircraft. All charter quotes are generated by our charter network partners.';
  const pages = [];
  const walk = (dir) => {
    for (const f of readdirSync(dir)) {
      const p = join(dir, f);
      if (statSync(p).isDirectory()) walk(p);
      else if (f === 'index.html') pages.push(p);
    }
  };
  walk(join(ROOT, 'dist'));
  pages.push(join(ROOT, 'dist/404.html'));
  const missing = pages.filter((p) => !readFileSync(p, 'utf8').includes(needle));
  if (missing.length) throw new Error(`missing on ${missing.length} pages, e.g. ${missing[0]}`);
  return `${pages.length}/${pages.length} pages`;
});

// ---- server-dependent suites -----------------------------------------------
const alive = await fetch('http://localhost:4321/', { signal: AbortSignal.timeout(1500) })
  .then((r) => r.ok)
  .catch(() => false);
let server = null;
if (!alive) {
  server = spawn('npx', ['astro', 'preview', '--port', '4321'], { cwd: ROOT, stdio: 'ignore' });
  for (let i = 0; i < 20; i++) {
    await new Promise((r) => setTimeout(r, 500));
    if (await fetch('http://localhost:4321/').then((r) => r.ok).catch(() => false)) break;
  }
}

for (const suite of [
  'verify_nav.mjs',
  'verify_ga_events.mjs',
  'verify_quote_fallback.mjs',
  'verify_operator_finder.mjs',
  'verify_form_signals.mjs',
]) {
  run(suite, () => {
    const out = execSync(`node scripts/${suite}`, { cwd: ROOT, encoding: 'utf8' });
    const m = out.match(/(\d+)\/(\d+) checks passed/);
    if (!m || m[1] !== m[2]) throw new Error(out.split('\n').filter((l) => l.startsWith('FAIL')).join('; ') || 'no pass line');
    return `${m[1]}/${m[2]}`;
  });
}

server?.kill();
const passed = results.filter(Boolean).length;
console.log(`\n${passed}/${results.length} suites passed`);
process.exit(passed === results.length ? 0 : 1);
